auth_demo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts import views as accounts_views
from hello import views as hello_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^$', hello_views.get_index, name='index'),
    url(r'^form/',hello_views.test_form,name='test_form'),
    url(r'^todo/', include('todo.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^entertainer/', include('entertainer.urls')),
    url(r'^blog/', include('blog.urls')),
    #url(r'', include('blog.urls'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url
import views

app_name = 'blog'

urlpatterns = [
    url(r'^list/$', views.post_list, name="list"),
]

entertainer/urls.py
from django.conf.urls import url
from rest_framework_jwt.views import obtain_jwt_token
from entertainer import views
from accounts.views import UserView

app_name = 'entertainer'


urlpatterns = [
    url(r'^create_profile/$', views.create_profile, name='create_profile'),
    url(r'^listings/$', views.listings, name='listed_entertainers'),
]

entertainer/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from accounts.models import User
from django.db import models


# Create your models here.
class Entertainer(models.Model):
    #   DEFINE CHOICES LISTS WITH CONSTANTS
    ENT_TYPES = (
        ('Band', 'Band'),
        ('Solo', 'Solo')
    )
    GENRE_TYPES = (
        ('Rock', 'Rock'),
        ('Metal', 'Metal'),
        ('Punk', 'Punk'),
        ('Blues', 'Blues'),
        ('Jazz', 'Jazz'),
        ('Classical', 'Classical'),
        ('Reggae', 'Reggae'),
        ('Ska', 'Ska'),
        ('Dance', 'Dance'),
        ('Electronic', 'Electronic'),
        ('Folk', 'Folk'),
        ('Pop', 'Pop'),
        ('Funk', 'Funk'),
        ('Trad', 'Trad'),
        ('Country', 'Country'),
        ('Soul', 'Soul'),
        ('RnB','RnB'),
        ('Other', 'Other'),
    )

    #   An Entertainer is a User - One To One Relationship
    user = models.OneToOneField(User,
                                related_name='user')
    #   FIELDS
    title = models.CharField(
        max_length = 15
    )
    description = models.CharField(
        max_length = 14,
        choices = ENT_TYPES,
        default = 'Band'
    )
    genre = models.CharField(
        max_length = 11,
        choices = GENRE_TYPES,
        default = 'Rock'
    )
    profileImage = models.ImageField(
        upload_to = 'images/profile/',
        default='no_image.png'
    )

entertainer/forms.py
from django import forms
from entertainer.models import Entertainer


class EntertainerRegistrationForm(forms.ModelForm):

    #   User Object required to be created before Entertainer object
    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(EntertainerRegistrationForm,self).__init__(*args,**kwargs)

    #   Custom save function to include the User
    def save(self,commit=True):
        #   save(commit=False prevents the form from auto saving
        instance = super(EntertainerRegistrationForm,self).save(commit=False)

        # auto set the user instance to that provided by the view
        instance.user = self.user

        if commit:
            instance.save()

        return instance

    #   Fields to include on form from the Entertainer model
    class Meta:
        model = Entertainer
        fields = ('title',
                  'description',
                  'genre',
                  'profileImage')

entertainer/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from .forms import EntertainerRegistrationForm
from django.contrib.auth.decorators import login_required
from .models import Entertainer

# Create your views here.
@login_required
def create_profile(request):
    if request.method == 'POST':
        #   user bject is passed to the form class constructor
        form = EntertainerRegistrationForm(request.user,request.POST)
        if form.is_valid():
            #form.user = request.user
            form.save()
            args = {'message': 'Entertainer listing created'}
            return render(request, 'entertainer/profile_created.html',args)
    else:
        #   When the form is loaded initially
        #   must pass the newly created user object to it's constructor
        form = EntertainerRegistrationForm(request.user)
        return render(request, 'entertainer/create_profile.html', {'form': form})


def listings(request):
    entertainers = Entertainer.objects.all()
    return render(request, 'entertainer/listings.html',{'entertainers':entertainers})

entertainer/templates/entertainer/create_profile.html
{% extends 'base.html' %}
{% load bootstrap_tags %}
{% block content %}
    <div class="row">
        <div class="col-4">
            &nbsp;
        </div>
        <div class="col-4">
            <form role="form" method="post" action="{% url 'entertainer:create_profile' %}" class="account-form">
                <legend>Entertainer Profile</legend>
                <hr>
                {% csrf_token %}
                {{ form | as_bootstrap }}
                <div class="form-group">
                    <button type="submit" class="btn btn-orange btn-block">Create</button>
                </div>
            </form>
        </div>
        <div class="col-4">
            &nbsp;
        </div>
    </div>
{% endblock %}

entertainer/templates/entertainer/listings.html
{% extends 'base.html' %}
{% load bootstrap_tags %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-4">
            &nbsp;
        </div>
        <div class="col-4">
            Listed Entertainers
        </div>
        <div class="col-4">
            &nbsp;
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            &nbsp;
        </div>
        <div class="col-4">
            {% for entertainer in entertainers %}
                <div class="col-3 ent-listing">
                    {{ entertainer.title }}
                    <img class="card-img-top" src="{{ entertainer.profileImage.url }}" class="img-fluid center-block img-thumbnail" style="max-height:150px;" alt="Image">
                </div>
            {% endfor %}
        </div>
        <div class="col-4">
            &nbsp;
        </div>
    </div>
{% endblock %}
{% block script %}
    <script src="{% static "js/custom.js" %}"></script>
{% endblock %}

entertainer/templates/entertainer/profile_created.html
{% extends 'base.html' %}
{% load bootstrap_tags %}
{% block content %}
    <div class="row">
        <div class="col-4">
            &nbsp;
        </div>
        <div class="col-4">
            {{ message }}
        </div>
        <div class="col-4">
            &nbsp;
        </div>
    </div>
{% endblock %}