accounts/urls.py
from django.conf.urls import url
from rest_framework_jwt.views import obtain_jwt_token
from accounts import views
from accounts.views import UserView, auth_register

app_name = 'accounts'

urlpatterns = [
    url(r'^register/$', views.auth_register, name='register'),
    url(r'^profile/', views.auth_profile, name='profile'),
    url(r'^login/', views.auth_login, name='login'),
    url(r'^logout/', views.auth_logout, name='logout'),
    url(r'^test/', views.test, name='test'),
    url(r'^register_api/$',UserView.as_view()), # provide email and password
    #   JWT based on the username(email) and password
    url(r'^api-token-auth/$',obtain_jwt_token)  # provide email and password
]

auth_demo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts import views as accounts_views
from hello import views as hello_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^$', hello_views.get_index, name='index'),
    url(r'^form/',hello_views.test_form,name='test_form'),
    url(r'^todo/', include('todo.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^entertainer/', include('entertainer.urls')),
    url(r'^blog/', include('blog.urls')),
    #url(r'', include('blog.urls'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url
import views

app_name = 'blog'

urlpatterns = [
    url(r'^list/$', views.post_list, name="list"),
]

entertainer/urls.py
from django.conf.urls import url
from rest_framework_jwt.views import obtain_jwt_token
from entertainer import views
from accounts.views import UserView

app_name = 'entertainer'


urlpatterns = [
    url(r'^create_profile/$', views.create_profile, name='create_profile'),
    url(r'^listings/$', views.listings, name='listed_entertainers'),
]

todo/urls.py
from django.conf.urls import url
from todo.views import TodoView
from . import views

# specific app URL pointable from template
app_name = 'todo'

urlpatterns = [
    #   we need to invoke the as_view method on the TodoView class
    #   Any view that inherits from the base View object will have the as_view method
    #   This will allow Django to use the class-based view as a standard function-based view.
    url(r'^$',TodoView.as_view(), name='todo_all'),
    url(r'^todo_api_render/', views.todo_api_render, name='todo_api_render'),
    url(r'^(?P<pk>[0-9]+)/$',TodoView.as_view())
]


'''
    1 click link in base template to link to view
    2 view loads template containing the JSON REQUEST
    3 template renders the data
'''

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Custom Authentication Test Site</title>
    <meta name="viewport" content="width=device-width", initial-scale="1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.6/cerulean/bootstrap.min.css">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}">
</head>
<body>
    <div class="container">
        <div class="masthead">
            <ul class="nav nav-pills pull-right">
                <li><a href="#">Home</a></li>
                <li><a href="{% url 'todo:todo_api_render' %}">Todo API Render</a></li>
                <li><a href="{% url 'todo:todo_all' %}">Todo API</a></li>
                <li><a href="{% url 'accounts:register' %}">Register</a></li>
                <li><a href="{% url 'accounts:test' %}">Test</a></li>
                <li><a href="{% url 'entertainer:listed_entertainers' %}">Entertainers</a></li>
                <li><a href="{% url 'test_form' %}">Form</a></li>
                <li><a href="{% url 'blog:list' %}">Blog</a></li>
                {% if user.is_active %}
                    <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:login' %}">Log In</a></li>
                {% endif %}
            </ul>
            <h1><span class="fui-settings-16 muted">Our Simple Site</span></h1>
            <p id="logo" class="lead">The Trials of a Bootcamp Developer</p>
        </div>
        <hr>
        <br>
        {% if messages %}
            <div class="alert alert-success">
                <div class="messages">
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel">
                        <div class="panel-body">
                            {% block content %}
                            {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <footer>
            <div class="container">

            </div>
        </footer>
    </div>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% block script %}{% endblock %}
</html>